#!/usr/bin/env ruby

require 'bundler/setup'
require 'weather'
require 'slop'

opts = Slop.parse do |o|
  o.string '-s', '--service', 'a service', default: 'metaweather'
  o.string '-c', '--city', 'a city', default: 'moscow'
  o.string '-k', '--key', 'a key', default: ''
end

puts Weather::Weather.new(
  service_name: opts[:service],
  key: opts[:key]
).get_info(opts[:city])