#!/usr/bin/env ruby

require 'bundler/setup'
require 'weather'
require 'slop'

opts = Slop.parse do |o|
  o.string '-s', '--service', 'a service', default: 'metaweather'
  o.string '-c', '--city', 'a service', default: 'moscow'
end

puts Weather::Weather.new(opts[:service]).get_info(opts[:city])